### ISSUE TITLE
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at

### ISSUE THREAD

**Issue by thinkingingame** [xxl-job/xxl-job-executor-go#48]
执行器部署完了，浏览器中访问http://****:9977/run，返回
[{"logId":0,"logDateTim":0,"executeResult":{"code":500,"msg":"params err"},"handleCode":500,"handleMsg":"params err"}]
说明执行器部署没问题，网络也没问题。
然后admin中执行任务，报错：

任务触发类型：手动触发
调度机器：admin IP地址
执行器-注册方式：手动录入
执行器-地址列表：[****:9977]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：****:9977
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1662349128294, request:XxlRpcRequest{requestId='19136019-dee8-4611-bd7b-d8d501c67e1a', createMillisTime=1662349125222, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=1, executorHandler='testJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=35657, logDateTime=1662349125077, glueType='BEAN', glueSource='', glueUpdatetime=1541254891000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy93.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

有个类似的问题：https://github.com/xxl-job/xxl-job-executor-go/issues/29
不知道那个具体怎么配置，我的执行器也是部署在docker中。

**Comment by thinkingingame** [comment]
升级xxl-job解决了此问题
